# This is a basic workflow to help you get started with Actions

name: Sample CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #schedule:
  #  - cron: "*/5 * * * *"
  workflow_dispatch:
    inputs:
      customer:
        description: "Pleas select"
        required: true
        type: choice
        options:
          - ULTRA_HACK
          - ULTRA_BOX
          - ULTRA_FUCK
      operator:
        description: "Operator name"
        type: string
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Run luna
        run: |
          echo "Go to sleep"
          sleep 10
          echo "Rady luna"

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Test

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Luna barks
          echo Luna barks

      - name: Test input
        run: |
          echo "${CUSTOMER}"
          echo "${OPERATOR}"
        env:
          CUSTOMER: ${{ inputs.customer }}
          OPERATOR: ${{ inputs.operator }}
